source 'https://github.com/arceushs/AHPodSpecs'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'realMatch-OC' do

pod 'SVProgressHUD'
pod 'SocketRocket'
pod 'SDWebImage', '~> 5.0'
pod 'AFNetworking', '~> 3.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
pod 'GPUImage'
pod 'GPUImageBeautifyFilter'
pod 'AHTimer','~>0.0.3'
pod 'Realm'
pod 'Socket.IO-Client-Swift', '~> 15.1.0'
pod 'FMDB'
pod 'SnapKit', '~> 5.0.0'
pod 'TTTAttributedLabel'
pod 'AppsFlyerFramework'
#pod 'FBAudienceNetwork'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

end
