source 'https://github.com/arceushs/AHPodSpecs'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'realMatch-OC' do

pod 'AccountKit'
pod 'SVProgressHUD'
pod 'SocketRocket'
pod 'SDWebImage', '~> 5.0'
pod 'AFNetworking', '~> 3.0'
pod 'GPUImage'
pod 'GPUImageBeautifyFilter'
pod 'AHTimer','~>0.0.3'
pod 'Realm'
pod 'Socket.IO-Client-Swift', '~> 15.1.0'
pod 'FMDB'

end
